export const API_PREFIX = "/api/v1";

export const paths = {
  signIn: `${API_PREFIX}/auth/sign-in`,
  signUp: `${API_PREFIX}/auth/sign-up`,
  signOut: `${API_PREFIX}/auth/sign-out`,
  me: `${API_PREFIX}/auth/me`,
  explore: `${API_PREFIX}/explore`,
  search: `${API_PREFIX}/search`,
  class: (slug: string) => `${API_PREFIX}/classes/${encodeURIComponent(slug)}`,
  slots: `${API_PREFIX}/classes/slots`,
  teacher: (slug: string) => `${API_PREFIX}/teachers/${encodeURIComponent(slug)}`,
  bookings: `${API_PREFIX}/bookings`,
  bookingCancel: (id: string) => `${API_PREFIX}/bookings/${encodeURIComponent(id)}/cancel`,
  bookingReschedule: (id: string) => `${API_PREFIX}/bookings/${encodeURIComponent(id)}/reschedule`,
  wallet: `${API_PREFIX}/wallet`,
  purchasePack: `${API_PREFIX}/packs/purchase`,
  purchaseMembership: `${API_PREFIX}/memberships/purchase`,
  waiver: (slug: string) => `${API_PREFIX}/waivers/${encodeURIComponent(slug)}`,
  signWaiver: (slug: string) => `${API_PREFIX}/waivers/${encodeURIComponent(slug)}/sign`,
  notifications: `${API_PREFIX}/notifications`,
  notificationsRead: `${API_PREFIX}/notifications/read`,
  preferences: `${API_PREFIX}/preferences`,
  pushTokens: `${API_PREFIX}/push-tokens`,
  help: `${API_PREFIX}/help`,
  helpArticle: (slug: string) => `${API_PREFIX}/help/${encodeURIComponent(slug)}`,
  tickets: `${API_PREFIX}/tickets`,
  track: `${API_PREFIX}/track`,
  experiment: (key: string) => `${API_PREFIX}/experiments/${encodeURIComponent(key)}`,
} as const;

/** Path templates the live client calls. Tests check each one against docs/openapi.yaml. */
export const documentedPaths = [
  "/auth/sign-in",
  "/auth/sign-up",
  "/auth/sign-out",
  "/auth/me",
  "/explore",
  "/search",
  "/classes/{slug}",
  "/classes/slots",
  "/teachers/{slug}",
  "/bookings",
  "/bookings/{id}/cancel",
  "/bookings/{id}/reschedule",
  "/wallet",
  "/packs/purchase",
  "/memberships/purchase",
  "/waivers/{teacherSlug}",
  "/waivers/{teacherSlug}/sign",
  "/notifications",
  "/notifications/read",
  "/preferences",
  "/push-tokens",
  "/help",
  "/help/{slug}",
  "/tickets",
  "/track",
  "/experiments/{key}",
] as const;
