export const API_PREFIX = "/api/v1";

export const paths = {
  catalog: `${API_PREFIX}/catalog`,
  explore: `${API_PREFIX}/explore`,
  class: (slug: string) => `${API_PREFIX}/classes/${encodeURIComponent(slug)}`,
  teacher: (slug: string) => `${API_PREFIX}/teachers/${encodeURIComponent(slug)}`,
  quote: `${API_PREFIX}/quotes`,
  bookings: `${API_PREFIX}/bookings`,
  booking: (id: string) => `${API_PREFIX}/bookings/${encodeURIComponent(id)}`,
  bookingCancel: (id: string) => `${API_PREFIX}/bookings/${encodeURIComponent(id)}/cancel`,
  bookingReschedule: (id: string) => `${API_PREFIX}/bookings/${encodeURIComponent(id)}/reschedule`,
  bookingHelp: (id: string) => `${API_PREFIX}/bookings/${encodeURIComponent(id)}/help`,
  order: (id: string) => `${API_PREFIX}/orders/${encodeURIComponent(id)}`,
  orderConfirm: (id: string) => `${API_PREFIX}/orders/${encodeURIComponent(id)}/confirm`,
  wallet: `${API_PREFIX}/wallet`,
  signup: `${API_PREFIX}/auth/signup`,
  login: `${API_PREFIX}/auth/login`,
  google: `${API_PREFIX}/auth/google`,
  apple: `${API_PREFIX}/auth/apple`,
  verify: `${API_PREFIX}/auth/verify`,
  resend: `${API_PREFIX}/auth/resend-verification`,
  forgot: `${API_PREFIX}/auth/forgot`,
  reset: `${API_PREFIX}/auth/reset`,
  logout: `${API_PREFIX}/auth/logout`,
  me: `${API_PREFIX}/me`,
  pushTokens: `${API_PREFIX}/push-tokens`,
  notifications: `${API_PREFIX}/notifications`,
  notification: (id: string) => `${API_PREFIX}/notifications/${encodeURIComponent(id)}/read`,
  notificationPreferences: `${API_PREFIX}/notification-preferences`,
  faq: `${API_PREFIX}/faq`,
  tickets: `${API_PREFIX}/support-tickets`,
  track: `${API_PREFIX}/track`,
  experiments: `${API_PREFIX}/experiments`,
} as const;
